## O problema de Monty Hall 

<p>O presente código, neste <i>Notebook</i>, simula através de uma demonstração empírica o problema e avalia as probabilidades associadas à cada situação apresentada ao jogador. Sejam elas:
<p>1. Quais as chances, em termos de probabilidade, do jogador encontrar um carro se ele <b>sempre trocar de porta</b>?
<p>2. E se o jogador permaner sempre com a primeira escolha, ou seja, <b>nunca trocar de porta</b>? 
<p>3. Avaliou-se também a probabilidade associada se o jogador, aleatoriamente, <b>manter a porta escolhida ou trocar</b>.

<p>Mais sobre o problema em: https://pt.wikipedia.org/wiki/Problema_de_Monty_Hall

<img src="Monty_hall_problem.jpg"/>

In [2]:
# import das bibliotcas necessárias
import pandas as pd
import numpy as np

In [10]:
# Configurando a situação inicial para apresentação do problema ao jogador
doors = np.array([0, 0, 0]) # Cria uma lista inicial
doors[np.random.choice([0,1,2])] = 1 # escolhe aleatoriamente uma posição e atualiza para o valor 1 
                                     # (colocando o carro atrás de uma das portas)
doors

array([0, 1, 0])

In [11]:
# Primeira escolha -> o jogador escolha a porta
#i_choice_1 = np.random.randint(3, size=1)[0]
i_choice_1 = np.random.choice([0,1,2])
i_choice_1 , #doors[i_choice_1]

(1,)

In [12]:
# O apresentador abre uma porta (não escolhida pelo jogador) contendo um bode                               # essa parte serve para 
i_choice_x = [x for x in [0,1,2] if not x==i_choice_1 and not doors[x]==1]#[ np.random.randint(2, size=1)[0] ]
i_choice_x

[0, 2]

In [30]:
# Segunda escolha -> jogador. O apresentador pergunta ao jogador se ele escolhe outra porta ou mantém a porta ecolhida
# se for igual a True ele manteve a porta escolhida, caso contrário ele trocou de porta
i_other_door = i_other_door = [x for x in [0,1,2] if x!=i_choice_1 and x!=i_choice_x[0]]

i_choice_2 = np.random.choice([i_choice_1,i_other_door[0]])

(i_choice_2 == i_choice_1)

False

In [36]:
# O Jogador, então, abre a porta escolhida.
# Se for igual a 1 (True) ele ganhou o carro, caso contrário ele ganhou um bode.
doors[i_choice_2] == 1 

False

In [37]:
# essa função simula uma roda de escolhas para o problema 
def monty_hall_problem(change_door=0):
    """
    change_door == 0 => troca de porta sempre
    change_door == 1 => nunca troca de porta
    change_door == other value => escolhe aleatoriamente entre a porta autal e a outra porta
    """
    doors_index = [0,1,2]
    
    # Configura a situação inicial
    doors = np.array([0, 0, 0]) # Cria uma lista inicial com valores zero (bodes)
    doors[np.random.choice(doors_index)] = 1 # escolhe aleatoriamente uma porta e atualiza para o valor 1 (carro)

    # Primeira escolha -> jogador escolhe aleatoriamente uma porta
    door_1 = np.random.choice(doors_index)
    
    # Apresentador abre uma porta (dentre as duas opçoões disponíveis) contendo um 0 (bode)
    door_x = np.random.choice([x for x in doors_index if x!=door_1 and doors[x]!=1]) # pega o elemento na posição 0 ou 1. 
    
    # Esse passo serve para identificar a outra porta disponível ao jogador excluída a que ele já escolheu
    other_door = [x for x in doors_index if x!=door_1 and x!=door_x][0]
    
    # Segunda escolha -> jogador. Ou ele muda de porta ou mantém a porta atual escolhida
    if change_door == 0: # sempre troca de porta
        door_2 = other_door
    elif change_door == 1: # nunca troca de porta
        door_2 = door_1
    else: # troca ou não, de porta
        door_2 = np.random.choice([door_1, other_door])
        
    # Abre a porta escolhida 
    return doors[door_2]

In [47]:
# Alguns testes 
for _ in range(10):
    print("Vc ganhou um carro :)" if monty_hall_problem(1) == 1 else "Vc ganhou um bode ;(")

Vc ganhou um bode ;(
Vc ganhou um carro :)
Vc ganhou um carro :)
Vc ganhou um bode ;(
Vc ganhou um bode ;(
Vc ganhou um bode ;(
Vc ganhou um carro :)
Vc ganhou um bode ;(
Vc ganhou um carro :)
Vc ganhou um carro :)


In [48]:
n_runs = 100000

In [49]:
%%time 

r1 = sum([monty_hall_problem(0) for _ in range(n_runs) ])/n_runs # sempre troca de porta
r2 = sum([monty_hall_problem(1) for _ in range(n_runs) ])/n_runs # nunca troca de porta
r3 = sum([monty_hall_problem(2) for _ in range(n_runs) ])/n_runs # troca ou não de porta

print( "Chances de ganhar se sempre trocar de porta: {0:3.0f}%\n \
Chances de ganhar se nunca trocar de porta: {1:3.0f}%\n \
Chances de ganhar se trocar ou não de porta: {2:3.0f}%".format(r1*100, r2*100, r3*100) )

Chances de ganhar se sempre trocar de porta:  67%
 Chances de ganhar se nunca trocar de porta:  33%
 Chances de ganhar se trocar ou não de porta:  50%
Wall time: 9.15 s


In [1]:
# Alguns calculos auxiliares

In [56]:
# escolha aleatório com probabilidades associadas -> tipo uma roleta viciada
[np.random.choice([1, 2, 3],p=[.4,.5,.1],size=1,replace=False) for _ in range(10)]

[array([1]),
 array([2]),
 array([2]),
 array([2]),
 array([1]),
 array([3]),
 array([1]),
 array([1]),
 array([2]),
 array([1])]

In [1558]:
i=0
while not np.random.choice(31,1) == [np.random.choice(range(31))]: i += 1
print(i)

20


In [1577]:
n_run=1000
np.sum([np.random.choice([0,1],p=[.39,.61]) for _ in range(n_run)])/n_run * 100

61.6